### PR TITLE
Document Cryptographic Payload

### PR DESCRIPTION
**Pull request by dkg**
This is a wordy but unambiguous description of the Cryptographic
Envelope and Cryptographic Payload concepts.

It makes use of the new xml2rfc v3 format, which lets us use non-ASCII
UTF-8 text in all forms of the document.

### CODE REVIEW

**Review by BjarniRunar — APPROVED** [review]
I have a general comment about this; although I absolutely agree with your recommendations that tools not generate complex structures, I also feel such guidelines are out of scope for Protected Headers. It's correct but off-topic.

Also, a question: do you consider the signature part in a multipart/signed to be part of the envelope? I would, but the text here implies it is not. I would also consider the trailing boundary strings to be part of the envelope, but omitting those is admittedly less notable than the signature part itself.

Further... are we sure these concepts necessary? I agree they're useful in a general sort of way when talking about these things, but I am not entirely sure the spec needs them. On the other hand, my definitions were clearly insufficient. I think I will sleep on it and either retract this scepticism or propose an alternative...

I really like the tree diagrams, they're very good!

**Comment by dkg** [comment]
thanks for the review, @BjarniRunar .

I've removed the guidance about what PGP/MIME structures to generate.

On the big picture: i am convinced that these concepts are necessary pre-requisites for a simple explanation of where to put the protected headers.  In addition, they are useful concepts for providing users with a sense of the cryptographic state of the message itself (most users can't or won't understand different cryptographic state for different subparts), and for talking about message structure more generally.

However, another option would be to produce a separate draft that is *just* about the cryptographic envelope and cryptographic payload, and reference that draft in this one.  Then we could also reference the same draft in a document that is more opinionated about MIME structure.

But i'm wary of a proliferation of drafts -- i don't want MUA implementers to feel like they have to read many documents to get good guidance about what to do.

**Comment by dkg** [comment]
a separate draft on Cryptographic Message Structure might also be useful in pulling in edits from S/MIME people without having them have to "buy in" to the rest of this draft.  i don't know whether that's actually useful though -- maybe we want that buy-in.

**Comment by dkg** [comment]
Also: i'm not sure how you read the draft to say that the signature is not a part of the Cryptographic Envelope for multipart/signed.  Can you maybe offer a suggestion for how to fix it?

As i read it (and as i've intended it, though may be failing at communicating), the Cryptographic Layer for multipart-signed is all the stuff around the "protected part", and the Cryptographic Envelope is the series of nested external contiguous Cryptographic Layers.  So the signature part is part of the layer, and the layer is part of the envelope.

I'm not sure what to make of your comment about the MIME boundaries.  I don't think they're relevant to this discussion -- a boundary is by definition *outside* of the thing that it delimits.  So the payload doesn't contain the boundary around it (though it may contain internal boundaries if it is itself multipart).

**Review by juga0 — APPROVED** [review]
I find it a bit hard to read, i think i've understood the concepts, i'll think about how this could be explained in a simpler way

**Comment by juga0** [comment]
Ah, and the diagrams look great with UTF-8! :)

**Pull request merged**
