### PR TITLE
Avoid leaking Obscured Headers in reply

### PR DESCRIPTION
**Pull request by dkg**
This is a key piece of functional guidance for implementers that want
to securely manage protected headers.

### CODE REVIEW

**Review by juga0 — APPROVED** [review]
lgtm

**Review by BjarniRunar — CHANGES_REQUESTED** [review]
I have quibbles! :-)

First of all, I think in your intro paragraph you're again giving correct advice that is out of scope for the spec. If we're only discussing headers, we don't get to MUST or SHOULD about the rest of the content...

But in general, what you have stated here is a very hard to satisfy requirement; what it means in reality is that if one MUA decides to obscure some header content, then the receiving MUA is in violation of the spec if it doesn't implement all the same strategies to obscure information, in the same way.

Since nobody is going to implement all the same stratgies as everyone else (this requirement cannot realistically be satisfied in a complex world), this would dictate that a complaint MUA blindly copy the content of any received Protected Headers into the outgoing message in the same way, and preserve the differences between Exposed and Protected even while making whatever changes were dictated by the reply algorithm. I'm not even sure how I would write such code.

This is a decidedly non-trivial burden to implementors, and there may even be security considerations because you're effectively saying that the sender gets to dictate how you construct your outgoing message.

So I think for practical reasons, your MUST can never be more than a SHOULD.

**Comment by dkg** [comment]
Thanks for keeping me honest and in-scope, @BjarniRunar 

I've just pushed an update that i think resolves your concern.  could you review the new version?

**Review by BjarniRunar — APPROVED** [review]
Awesome! I'm gonna click the merge button.

**Pull request merged**
